/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthGlass: typeof import('./src/components/AuthGlass.vue')['default']
    Button: typeof import('primevue/button')['default']
    FloatingNavbar: typeof import('./src/components/FloatingNavbar.vue')['default']
    ForgotPasswordGlass: typeof import('./src/components/ForgotPasswordGlass.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}
