services:
  auth-service:
    depends_on:
      - db
    container_name: auth-service
    image: auth-service:latest
    environment:
      - PG_URL=db
      - PG_USERNAME=user-name
      - PG_PASSWORD=strong-password
      - PG_DATABASE=brewget
      - CORS_URL=http://localhost
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=86400
      - JWT_MAX_AGE=86400
    networks:
      - db
  email-service:
    container_name: email-service:latest
    image: email-service:latest
    environment:
      - SMTP_EMAIL=noreply@brewingbytes.com
      - SMTP_NAME=BrewGet
      - SMTP_RELAY=smtp.example.com
      - SMTP_USERNAME=smtp-user
      - SMTP_PASSWORD=smtp-password
    networks:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  db:
  pgadmin:
