---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: brewget
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres

---
# PersistentVolume using hostPath to store data
# The deploy.sh script automatically mounts ~/.brewget-data/postgres (host machine)
# to /data/brewget-postgres (inside minikube) for true persistence across minikube deletions
# 
# This ensures data persists even when minikube is completely deleted and recreated
# See k8s/README.md for more details on persistent storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewget-postgres-pv
  labels:
    type: local
    app: postgres
spec:
  # Empty storageClassName explicitly opts out of dynamic provisioning
  # This allows manual binding using the label selector below
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # This path is inside minikube and is mounted to ~/.brewget-data/postgres on host
    # The deploy.sh script handles the mounting automatically
    path: "/data/brewget-postgres"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---
# PersistentVolumeClaim that binds to the hostPath PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewget-postgres-pvc
  namespace: brewget
spec:
  # Empty storageClassName must match the PV to enable manual binding
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: local
      app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: brewget
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: brewget-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brewget-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: brewget-postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init
            defaultMode: 0755
