---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: brewget
  labels:
    app: auth-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 9000
      targetPort: 9000
      name: grpc
  selector:
    app: auth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: brewget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:16-alpine
        command:
          - sh
          - -c
          - |
            until pg_isready -h db -U $POSTGRES_USER; do
              echo "Waiting for database..."
              sleep 2
            done
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: brewget-secrets
              key: postgres-user
      - name: wait-for-email-service
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z email-service 9001; do
              echo "Waiting for email service..."
              sleep 2
            done
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: auth-service
        image: ghcr.io/brewingbytes/brewget-auth-service:0.0.8
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: grpc
        env:
        - name: PG_URL
          value: db
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: brewget-secrets
              key: postgres-user
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: brewget-secrets
              key: postgres-password
        - name: AUTH_PG_DATABASE
          value: brewget_auth
        - name: CORS_URL
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: CORS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: brewget-secrets
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          value: "86400"
        - name: JWT_MAX_AGE
          value: "86400"
        - name: AUTH_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: AUTH_HTTP_PORT
        - name: AUTH_GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: AUTH_GRPC_PORT
        - name: EMAIL_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: EMAIL_HOSTNAME
        - name: EMAIL_GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: EMAIL_GRPC_PORT
        - name: FRONTEND_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: FRONTEND_HOSTNAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
