---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: brewget
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: brewget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: setup-certs
        image: alpine:3.18
        command:
          - sh
          - -c
          - |
            # Install OpenSSL
            apk add --no-cache openssl
            
            # Check if Let's Encrypt certificates exist
            if [ -f /etc/nginx/ssl/fullchain.pem ] && [ -f /etc/nginx/ssl/privkey.pem ]; then
              echo "Let's Encrypt certificates found, using them"
              exit 0
            fi
            
            echo "Let's Encrypt certificates not found, generating self-signed certificates"
            
            # Generate self-signed certificate
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout /etc/nginx/ssl/privkey.pem \
              -out /etc/nginx/ssl/fullchain.pem \
              -subj "/C=US/ST=State/L=City/O=Organization/CN=brewget.brewingbytes.com"
            
            echo "Self-signed certificates generated successfully"
            echo "WARNING: Using self-signed certificates. Please configure Let's Encrypt for production use."
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/ssl
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      - name: wait-for-frontend
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z frontend 80; do
              echo "Waiting for frontend..."
              sleep 2
            done
      - name: wait-for-auth-service
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z auth-service 8000; do
              echo "Waiting for auth service..."
              sleep 2
            done
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: tls-certs
          mountPath: /etc/nginx/ssl
          readOnly: true
        - name: certbot-webroot
          mountPath: /var/www/certbot
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: tls-certs
        hostPath:
          path: /etc/letsencrypt/live/brewget.brewingbytes.com
          type: DirectoryOrCreate
      - name: certbot-webroot
        emptyDir: {}
