on:
  push:
    branches:
      - main

name: Backend Docker Build
jobs:
  docker:
      name: Build Backend Docker Images
      permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
      defaults:
        run:
          working-directory: ./backend
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: dorny/paths-filter@v3
          id: changes
          name: Changes
          with:
            filters: |
              auth:
                - 'backend/auth-service/Cargo.toml'
        - name: Cache
          uses: actions/cache@v4
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        - name: Build base-image
          run: docker build -t base-image .
        - name: Get auth-service version
          if: steps.changes.outputs.auth == 'true'
          id: get_version
          run: |
            VERSION=$(grep '^version = ' ./auth-service/Cargo.toml | sed -n 's/^version = "\(.*\)"/\1/p')
            echo "auth_version=$VERSION" >> "$GITHUB_OUTPUT"
        - name: Build auth-service image
          if: steps.changes.outputs.auth == 'true'
          run: |
              docker build -t auth-service auth-service
              docker tag auth-service ghcr.io/brewingbytes/brewget-auth-service:${{ steps.get_version.outputs.auth_version }}
              docker tag auth-service ghcr.io/brewingbytes/brewget-auth-service:latest
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push auth-service
          if: steps.changes.outputs.auth == 'true'
          run: |
              docker push ghcr.io/brewingbytes/brewget-auth-service:${{ steps.get_version.outputs.auth_version }}
              docker push ghcr.io/brewingbytes/brewget-auth-service:latest

          
          
